// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkJF9wtxf25j99eY2NXRyt04_5CFLlxOs',
    appId: '1:462217540932:web:6d65386052f25bec819311',
    messagingSenderId: '462217540932',
    projectId: 'mycarpool-556cf',
    authDomain: 'mycarpool-556cf.firebaseapp.com',
    storageBucket: 'mycarpool-556cf.firebasestorage.app',
    measurementId: 'G-XPPM2X5DX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO8p_uc7HnkzFG5cE_2bPi35M9k1UNrr4',
    appId: '1:462217540932:android:4d1f95a7d88d165e819311',
    messagingSenderId: '462217540932',
    projectId: 'mycarpool-556cf',
    storageBucket: 'mycarpool-556cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ZvohLYJ2fbMIg4vgvVGsWDLQ54qbEJU',
    appId: '1:462217540932:ios:7bd29f55ad7c8986819311',
    messagingSenderId: '462217540932',
    projectId: 'mycarpool-556cf',
    storageBucket: 'mycarpool-556cf.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ZvohLYJ2fbMIg4vgvVGsWDLQ54qbEJU',
    appId: '1:462217540932:ios:7bd29f55ad7c8986819311',
    messagingSenderId: '462217540932',
    projectId: 'mycarpool-556cf',
    storageBucket: 'mycarpool-556cf.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkJF9wtxf25j99eY2NXRyt04_5CFLlxOs',
    appId: '1:462217540932:web:cfbfc4c153ad7816819311',
    messagingSenderId: '462217540932',
    projectId: 'mycarpool-556cf',
    authDomain: 'mycarpool-556cf.firebaseapp.com',
    storageBucket: 'mycarpool-556cf.firebasestorage.app',
    measurementId: 'G-9EN7YZJ3SY',
  );
}
